### ISSUE TITLE
0.6.0 release

### ISSUE THREAD

**Issue by till** [lagged/apt-spy2#17]
## Changelog

TL;DR — Nothing new, just house keeping.

 - [x] Security updates/fixes (in dependencies): `rest-client` #12 , `nokogiri` #16 
 - [x] Dependency updates: `thor` #10 , `json` #13 , `rake` #11 
 - [x] (Potential) BC breaks:
   - switched to Ruby 2.5.1 (from 1.9.3) #15 
   - CI runs on latest LTS (at this time) #15 
 - [x] Bundler 2 update #14 
 - [x] Clarify license #18
 - [x] Add new test setup (add a `Dockerfile`) and remove Vagrant #19 
 - [x] Increment version #20 
 - [x] use `bundle exec rake release`
