### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by till** [lagged/apt-spy2#80]
- [x] update version
- [x] add a workflow with `--strict`
- [x] push 🥳

---

Changelog

- [x] updates nokogiri (to resolves lots of CVEs 🙈) #81 
- [x] ❗ ❗ ❗  drops support for ruby 2.6 (and adds 3.2.1) #81 
- [x] run rubocop on the code and fix obvious violations #83
- [x] #78
